import type { Metadata } from "next";
import localFont from "next/font/local";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const dancingScript = localFont({
  src: [
    {
      path: "./fonts/DancingScript-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/DancingScript-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/DancingScript-Semibold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/DancingScript-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-dancing-script",
});

const openSans = localFont({
  src: [
    {
      path: "./fonts/OpenSans-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/OpenSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/OpenSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/OpenSans-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/OpenSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-open-sans",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.variable} ${openSans.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
